# Generated by Django 4.0.3 on 2022-03-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followers_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
