# Generated by Django 4.0.3 on 2022-04-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='value',
            field=models.CharField(default='like', max_length=20),
        ),
    ]
