# Generated by Django 4.0.3 on 2022-04-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_postlike_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='value',
            field=models.CharField(choices=[('like', 'like'), ('unlike', 'unlike')], max_length=20),
        ),
    ]
