export const FETCH_POSTS = 'FETCH_POSTS'
export const CREATE_POST = 'CREATE_POST'
export const DELETE_POST  = 'DELETE_POST'
export const REST_POSTS = 'REST_POSTS'

export const FOLLOWING = 'FOLLOWING'
export const LIKE_UNLIKE_POST = "LIKE_UNLIKE_POST"
export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST'